### ISSUE TITLE
unable to login to an `iosxr` and `sros` device

### ISSUE THREAD

**Issue by nskalis** [CiscoTestAutomation/unicon.plugins#17]
Hi,

Thank you for making such a library available. Here is my experience with it:

---
- in regards to `junos`, all looking good.
---
- in regards to `sros`, I am waiting for [this PR](https://github.com/CiscoTestAutomation/unicon.plugins/pull/1/files) to land in `pip`, (but even without the asterisk) with `log_stdout` enable:
```
In [69]: uni_conn = unicon.Connection(hostname="x.x.x.x", credentials={"default": {"username": os.environ["USR_NETOPS"], "password": o
    ...: s.environ["PASS_NETOPS"]}}, os="sros", learn_hostname=True, start=["ssh {}".format("x.x.x.x")], )

2021-03-21 12:37:00,953: %UNICON-INFO: +++ x.x.x.x logfile /tmp/x_x_x_x-20210321T123700952.log +++

2021-03-21 12:37:00,953: %UNICON-INFO: +++ Unicon plugin sros +++

In [70]: uni_conn.connect()
...
__@x.x.x.x's password: 

2021-03-21 12:37:05,601: %UNICON-INFO: +++ connection to spawn: ssh -l __ x.x.x.x, id: 140305151131360 +++

2021-03-21 12:37:05,602: %UNICON-INFO: connection to x.x.x.x

A:a_hostname# 
```
The connection hangs and never returns (although successfully logins).

---
- in regards to `iosxr`, it doesn't recognise the RSP/CPU prompt (although it a library from Cisco)
```
In [71]: uni_conn = unicon.Connection(hostname="x.x.x.x", credentials={"default": {"username": os.environ["USR_NETOPS"], "password":
    ...: os.environ["PASS_NETOPS"]}}, os="iosxr", learn_hostname=True, start=["ssh {}".format("x.x.x.x")], )

2021-03-21 12:44:39,433: %UNICON-INFO: +++ x.x.x.x logfile /tmp/x_x_x_x-20210321T124439432.log +++

2021-03-21 12:44:39,433: %UNICON-INFO: +++ Unicon plugin iosxr +++

In [72]: uni_conn.connect()
Unable to negotiate with x.x.x.x port 22: no matching cipher found. Their offer: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc


2021-03-21 12:44:42,854: %UNICON-INFO: +++ connection to spawn: ssh -l __ x.x.x.x, id: 140305378210048 +++

2021-03-21 12:44:42,855: %UNICON-INFO: connection to x.x.x.x

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/unicon/eal/backend/pty_backend.cpython-38-x86_64-linux-gnu.so in unicon.eal.backend.pty_backend.RawPtySpawn._read()

OSError: [Errno 5] Input/output error

The above exception was the direct cause of the following exception:

EOF                                       Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/unicon/statemachine/statemachine.cpython-38-x86_64-linux-gnu.so in unicon.statemachine.statemachine.StateMachine.go_to()

~/.local/lib/python3.8/site-packages/unicon/statemachine/statetransition.cpython-38-x86_64-linux-gnu.so in unicon.statemachine.statetransition.AnyStateTransition.do_transitions()

~/.local/lib/python3.8/site-packages/unicon/eal/backend/pty_backend.cpython-38-x86_64-linux-gnu.so in unicon.eal.backend.pty_backend.RawSpawn.expect()

~/.local/lib/python3.8/site-packages/unicon/eal/backend/pty_backend.cpython-38-x86_64-linux-gnu.so in unicon.eal.backend.pty_backend.RawSpawn.read_update_buffer()

~/.local/lib/python3.8/site-packages/unicon/eal/backend/pty_backend.cpython-38-x86_64-linux-gnu.so in unicon.eal.backend.pty_backend.RawSpawn.read()

~/.local/lib/python3.8/site-packages/unicon/eal/backend/pty_backend.cpython-38-x86_64-linux-gnu.so in unicon.eal.backend.pty_backend.RawPtySpawn._read()

EOF: ('Unable to read. Connection closed or not available', OSError(5, 'Input/output error'))

The above exception was the direct cause of the following exception:

StateMachineError                         Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/unicon/bases/connection.cpython-38-x86_64-linux-gnu.so in unicon.bases.connection.Connection.connect()

~/.local/lib/python3.8/site-packages/unicon/bases/routers/connection_provider.cpython-38-x86_64-linux-gnu.so in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.connect()

~/.local/lib/python3.8/site-packages/unicon/bases/routers/connection_provider.cpython-38-x86_64-linux-gnu.so in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.establish_connection()

~/.local/lib/python3.8/site-packages/unicon/statemachine/statemachine.cpython-38-x86_64-linux-gnu.so in unicon.statemachine.statemachine.StateMachine.go_to()

StateMachineError: Failed while bringing device to "any" state

The above exception was the direct cause of the following exception:

ConnectionError                           Traceback (most recent call last)
<ipython-input-72-f0137236f6fa> in <module>
----> 1 uni_conn.connect()

~/.local/lib/python3.8/site-packages/unicon/bases/connection.cpython-38-x86_64-linux-gnu.so in unicon.bases.connection.Connection.connect()

ConnectionError: failed to connect to x.x.x.x
Failed while bringing device to "any" state
```
While the actual prompt is
```
__@x.x.x.x's password: 


RP/0/RSP0/CPU0:a_hostname#
```
---

Would you be so kind to advise if I am doing somthing wrong?

**Comment by ThomasJRyan** [comment]
Hello,

If I'm understanding the issue you may need to set the `learn_hostname` flag to `True` when you're connecting

`uni_conn.connect(learn_hostname = True)`

**Comment by nskalis** [comment]
```
In [6]: uni_conn.connect(learn_hostname = True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-d831b3b534c0> in <module>
----> 1 uni_conn.connect(learn_hostname = True)

~/.local/lib/python3.8/site-packages/unicon/bases/connection.cpython-38-x86_64-linux-gnu.so in unicon.bases.connection.Connection.connect()

TypeError: connect() got an unexpected keyword argument 'learn_hostname'
```

I guess it is not allowed. the docs say that it is a keyword argument in the initialisation of the `Connection` object.

**Comment by ThomasJRyan** [comment]
I've noticed you're not using the testbed file to create your connection. I would suggest using that rather than creating the components manually

https://pubhub.devnetcloud.com/media/pyats/docs/topology/creation.html#testbed-file

**Comment by nskalis** [comment]
Hi, I am not interested in using `pyats` at the moment hence I do not understand the indirection.
The above doesn't answer why `sros` hangs after log in. And, `iosxr` failing to understand the prompt.

This is the very first issue in this repository, and concerns 2 out of 3 vendors encountered in core networks.

Did you try to login in such boxes with the above code? Did you succeed? If no, what happened?
Are you able to replicate the issue and suggest a fix?

**Comment by ThomasJRyan** [comment]
Please look into this https://pubhub.devnetcloud.com/media/unicon/docs/user_guide/connection.html#extend-settings-attributes

It's likely your prompt isn't being matched and that is why your connection is hanging. 

You can look here to find which settings you can modify
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/generic/settings.py
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/iosxr/settings.py

**Comment by nskalis** [comment]
Hi. I looked into it. @ThomasJRyan would you be so kind to suggest what to try out specifically?

In case of `sros`:
Extending settings attributes do not apply when there is not a single command issued. 
Actually the problem described above is that it doesn't give the control back to the program (there is no error encountered).

In case of `iosxr`:
The example prompt provided does not match any of these patterns https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/iosxr/patterns.py

@danielgraziano I noticed that you're triaging this library's issue, can you help us out please?
I would appreciate it since this concerns 2 out of 3 vendors encountered in core networks.

**Comment by dwapstra** [comment]
@nskalis Hi Nikos, apologies for the delay in follow-up. Regarding the SROS connection issue, can you try with the latest (21.3) release and make sure the hostname matches the the device? If you are still having issues, you can email pyats-support-ext@cisco.com with the logs. Make sure the logs in include the traceback that happens after the timeout (usually around 60 seconds).

For the IOSXR issue, looks like your SSH client is not able to connect due to cipher negotiation failing. 
```
Unable to negotiate with x.x.x.x port 22: no matching cipher found. Their offer: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
```
you can add the option `-c aes128-cbc` to your SSH command to address this.

**Comment by nskalis** [comment]
@dwapstra thank you for looking at it.

in regards of `iosxr` that did the trick, I just found out that in modern versions of ssh the `cbc` algorithms are considered vulnerable, but that concerns the router I guess mostly.

When `unicon` connects to an `iosxr` device, it commits the following configuration by default:
```
Building configuration...
!! IOS XR Configuration 5.3.4
logging console disable
line console
 exec-timeout 0 0
 absolute-timeout 0
 session-timeout 0
!
line default
 exec-timeout 0 0
 absolute-timeout 0
 session-timeout 0
!
end
```

Is there a way to disable this activity?

In regards of `sros`, there is some progress, but not there still. I'll follow up via email. Thanks!
