### ISSUE TITLE
un-desirable config commit (and not documented?) upon connection with a `iosxr` device

### ISSUE THREAD

**Issue by nskalis** [CiscoTestAutomation/unicon.plugins#21]
Hi,

when unicon connects to an `iosxr` device, it commits the following configuration **by default**:

```
Building configuration...
!! IOS XR Configuration 5.3.4
logging console disable
line console
 exec-timeout 0 0
 absolute-timeout 0
 session-timeout 0
!
line default
 exec-timeout 0 0
 absolute-timeout 0
 session-timeout 0
!
end
```

Is there a way to disable this step? I cannot find where that is documented.

PS. the same question was asked in https://github.com/CiscoTestAutomation/unicon.plugins/issues/17 but the issue was closed...

**Comment by dwapstra** [comment]
@nskalis most plugins have setting for initial config. For IOSXR you can find them here https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/iosxr/settings.py#L13 .  To disable this, use `device.connect(init_config_commands=[])` or set the `init_config_command` argument in the topology file, see https://pubhub.devnetcloud.com/media/unicon/docs/user_guide/connection.html#customizing-your-connection.

**Comment by nskalis** [comment]
awesome! thank you!
