### ISSUE TITLE
SROS plugin does not work correctly with json output

### ISSUE THREAD

**Issue by SamiKeskiKasari** [CiscoTestAutomation/unicon.plugins#55]
It is possible to get configuration as json string via cli with command:
"admin show configuration json ....".
Currently the mdcli prompt regex breaks the output if there is json array in the response.

In release 21.x the context part seems be updated to include the path not just the brackets without any content.
Like [/] if in the root level.
So that probably would make easier to match correctly with regex.

In order to keep backward compatibility, I think that the current regex could be modified to not allow carriage return or new line in the context part. Like this:
```
--- a/src/unicon/plugins/sros/patterns.py
+++ b/src/unicon/plugins/sros/patterns.py
@@ -9,6 +9,6 @@ class SrosPatterns(UniconCorePatterns):
         super().__init__()
         self.continue_connect = r'Are you sure you want to continue connecting \(yes/no(/\[fingerprint\])?\)'
         self.permission_denied = r'^Permission denied, please try again\.\s?$'
-        self.mdcli_prompt = r'^(.*?)\[.*\][\r\n]+[AB]:.*@%N#\s?$'
+        self.mdcli_prompt = r'^(.*?)\[(?![\r\n]).*\][\r\n]+[AB]:.*@%N#\s?$'
         self.classiccli_prompt = r'^(.*?)\*?[AB]:%N(>.*)?#\s?$'
         self.discard_uncommitted = r'Discard uncommitted changes\? \[y,n\]'
```

**Comment by Taarini** [comment]
Hi @SamiKeskiKasari, Can you please contribute for fix.

**Comment by Taarini** [comment]
Please provide an update, if not the case will be closed after 30 days.

**Comment by SamiKeskiKasari** [comment]
Ok, I will create patch

**Comment by Taarini** [comment]
Closing this issue since you will be creating a new PR for the above
