### ISSUE TITLE
Inconsistent output format for "echo $?" command on Linux

### ISSUE THREAD

**Issue by mehran12623** [CiscoTestAutomation/unicon.plugins#85]
Hello
function post_service in The Linux Execute class expects the output of the "echo $?" command to end with a carriage return character followed by a newline character (\r\n) on Linux systems.
But in the Linux system that I tested. Neither sh nor bash returns such a pattern. I think this pattern belongs to Windows. What type of shell or operating system was considered in this source code for which such regex was written?
<pre>
con.sendline('echo $?')
try:
      match = con.expect(r'\r\n\d+', timeout=timeout)
</pre>
Source code: [unicon.plugins/linux/service_implementation.py#L61](https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/linux/service_implementation.py#L61)

**Comment by SohanTirpude** [comment]
Hello @mehran12623,

These are the output of two sessions `bash` and `ssh`, in which you can clearly see the `\r(carriage return)` in the command output.

`bash` session output:

	2023-07-06 07:27:46,420: %UNICON-DEBUG: spawn session 'bash' is being launched. 	 

	2023-07-06 07:27:46,945: %UNICON-DEBUG: >>> Unicon Sending :: 'echo $?\r' 
	echo $? 
	0 
	(p311) %n@%m %1~ %#	 

	2023-07-06 07:27:47,042: %UNICON-DEBUG: <<< Unicon Got :: 'echo $?\r\n0\r\n(p311) %n@%m %1~ %# ' 

`ssh` session output:

	2023-07-06 07:26:40,080: %UNICON-DEBUG: spawn session 'ssh -l xxx <hostname>' is being launched.  

	2023-07-06 07:26:46,535: %UNICON-DEBUG: >>> Unicon Sending :: 'echo $?\r' 
	echo $? 
	0 
	<hostname>:~ > 

	2023-07-06 07:26:46,792: %UNICON-DEBUG: <<< Unicon Got :: 'echo $?\r\n0\r\n<hostname>:~ > '

Kindly let me know if you have any more questions/doubts.

**Comment by SohanTirpude** [comment]
Hello @mehran12623,

Did you get a chance to go through the logs provided by me? Kindly let me know if you have any other doubts.

**Comment by SohanTirpude** [comment]
Hello @mehran12623,

Did you get a chance to go through the logs provided by me? Kindly let me know if you have any other doubts.

**Comment by SohanTirpude** [comment]
Hello @mehran12623,

Is there any update on this? Kindly let me know.

**Comment by SohanTirpude** [comment]
Hello @mehran12623,

Did you get a chance to look at the logs shared by me? Kindly let me know if you have any doubts/questions.

**Comment by SohanTirpude** [comment]
Hello @mehran12623,

I am closing this issue because of no response. Kindly let me know if you have any doubts/questions on the logs shared by me.
